# Generated by Django 4.2.1 on 2023-05-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=40)),
                ('prezime', models.CharField(max_length=40)),
                ('dob', models.IntegerField()),
                ('ulica', models.CharField(max_length=50)),
                ('mjestoStanjovanja', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='karta',
            name='idProjekcija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.projekcija'),
        ),
        migrations.AlterField(
            model_name='karta',
            name='idKorisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.korisnik'),
        ),
    ]
