# Generated by Django 4.2.1 on 2023-05-12 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_1', '0002_korisnik_alter_karta_idprojekcija_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karta',
            name='idKorisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Korisnik',
        ),
    ]
