# Generated by Django 4.2.1 on 2023-05-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(choices=[('COM', 'comedy'), ('HORR', 'horror'), ('DRA', 'drama')], max_length=30)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
